[package]
name = "pushover-rs"
version = "0.3.18"
edition = "2021"
license = "MIT"
description = "A Rust client for Pushover (https://www.pushover.net)"
homepage = "https://github.com/Oscuro87/pushover-rs"
documentation = "https://docs.rs/pushover-rs/latest/"
repository = "https://github.com/Oscuro87/pushover-rs"
readme = "README.md"
keywords = [
    "pushover",
    "notification",
    "mobile",
    "desktop",
    "push"
]
authors = ["Emka877"]

[dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12.4", features = ["json", "blocking", "multipart"] }
serde = { version = "1.0.198", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.116"
ron = "0.9.0-alpha.0"

[features]
default = []

[[example]]
name = "usage"
path = "examples/usage.rs"

[[example]]
name = "usage-with-attachment"
path = "examples/usage_with_attachment.rs"
