[package]
name = "pushover-rs"
version = "0.2.5"
edition = "2018"
license = "MIT"
description = "A Rust client for Pushover (https://www.pushover.net)"
homepage = "https://github.com/Oscuro87/pushover-rs"
documentation = "https://docs.rs/pushover-rs/latest/"
repository = "https://github.com/Oscuro87/pushover-rs"
readme = "README.md"
keywords = ["pushover", "push-notifications", "notification", "client"]
authors = ["Oscuro87"]

[dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.6", features = ["json", "blocking", "multipart"] }
serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.71"
ron = "0.7.0"

[features]
default = []

[[example]]
name = "usage-example"
path = "examples/usage.rs"

[[example]]
name = "usage-with-attachment"
path = "examples/usage_with_attachment.rs"